name: Rust

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - 'docs-overrides/**'
      - 'images/**'
      - '*.md'
      - 'mkdocs.yml'
      - '*.png'
      - '*.py'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'docs-overrides/**'
      - 'images/**'
      - '*.md'
      - 'mkdocs.yml'
      - '*.png'
      - '*.py'
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          # Update this key to force a new cache
          prefix-key: "rust-lint-v1"
      - name: Run cargo-fmt
        run: cargo fmt --all -- --check
      - name: Run cargo-clippy
        run: cargo clippy -- -D warnings
      - name: Check
        run: cargo check --verbose --workspace --all-targets

  # Tests for spatialbench
  test-tests-spatialbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-test-tests-spatialbench-v1"
      - name: Tests (spatialbench)
        run: cargo test -p spatialbench --tests

  test-doc-spatialbench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-test-doc-spatialbench-v1"
      - name: Doc Tests (spatialbench)
        run: cargo test -p spatialbench --doc

  test-all-spatialbench-arrow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-test-all-spatialbench-arrow-v1"
      - name: All Tests (spatialbench-arrow)
        run: cargo test -p spatialbench-arrow

  test-all-spatialbench-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-test-all-spatialbench-cli-v1"
      - name: All Tests (spatialbench-cli)
        run: cargo test -p spatialbench-cli

  # documentation build
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "rust-docs-v1"
      - name: Build docs
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --no-deps --workspace
